name: Code Tunnel Runner

on:
  workflow_dispatch:

jobs:
  tunnel:
    runs-on: macos-26

    steps:
      - name: Install VS Code CLI
        run: |
          brew install --cask visual-studio-code

      - name: Start Code Tunnel
        run: |
          code tunnel --accept-server-license-terms

      - name: Keep runner alive
        run: |
          tail -f /dev/null
